### PR TITLE
Feature rename "Starting from a template" to "Getting started"

### PR DESCRIPTION
**Pull request by rylandg**
As the title says, renames the section "Starting from a Template" to "Getting Started". Previously it was not unified and caused users confusion.

https://github.com/binaris/dev-docs-content/issues/1

### CODE REVIEW

**Review by foundingnimo — CHANGES_REQUESTED** [review]
The changes here are fine.
The file generic-template-readme.md also contains a 'Starting from a template' link - should we get that changed as well?

**Comment by rylandg** [comment]
@duckranger No, the generic file is what users see when they initially remix the dev site. They won't have our doc pages and therefore relative links don't make sense.

**Comment by foundingnimo** [comment]
> @duckranger No, the generic file is what users see when they initially remix the dev site. They won't have our doc pages and therefore relative links don't make sense.

I meant the text - not the link itself?

**Comment by rylandg** [comment]
Ahhh I understand. Nice catch.

**Review by foundingnimo — APPROVED** [review]
Thanks! Sorry I wasn't clear enough in my comment

**Comment by rylandg** [comment]
It was my bad. Thanks again for catching it and re-explaining.

**Pull request merged**
